--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2024-10-13 17:18:55

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 24578)
-- Name: don_hang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.don_hang (
    id_don_hang bigint NOT NULL,
    ngay_dat date,
    id_khach_hang bigint,
    id_tai_khoan bigint,
    id_trang_thai bigint
);


ALTER TABLE public.don_hang OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 24577)
-- Name: don_hang_id_don_hang_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.don_hang ALTER COLUMN id_don_hang ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.don_hang_id_don_hang_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24584)
-- Name: khach_hang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.khach_hang (
    id_khach_hang bigint NOT NULL,
    dia_chi character varying(200),
    email character varying(100),
    so_dien_thoai character varying(10),
    ten_khach_hang character varying(100)
);


ALTER TABLE public.khach_hang OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24583)
-- Name: khach_hang_id_khach_hang_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.khach_hang ALTER COLUMN id_khach_hang ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.khach_hang_id_khach_hang_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 24590)
-- Name: nhacc; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nhacc (
    id_nha_cung_cap bigint NOT NULL,
    dia_chi character varying(200),
    email character varying(100),
    so_dien_thoai character varying(10),
    ten_nha_cung_cap character varying(100) NOT NULL
);


ALTER TABLE public.nhacc OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24589)
-- Name: nhacc_id_nha_cung_cap_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.nhacc ALTER COLUMN id_nha_cung_cap ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nhacc_id_nha_cung_cap_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24596)
-- Name: tai_khoan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tai_khoan (
    id_tai_khoan bigint NOT NULL,
    email character varying(100),
    mat_khau character varying(100),
    tentk character varying(50),
    vai_tro character varying(20)
);


ALTER TABLE public.tai_khoan OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24595)
-- Name: tai_khoan_id_tai_khoan_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tai_khoan ALTER COLUMN id_tai_khoan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tai_khoan_id_tai_khoan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24602)
-- Name: trang_thaidh; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trang_thaidh (
    id_trang_thai bigint NOT NULL,
    ten character varying(20)
);


ALTER TABLE public.trang_thaidh OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24601)
-- Name: trang_thaidh_id_trang_thai_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trang_thaidh ALTER COLUMN id_trang_thai ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trang_thaidh_id_trang_thai_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 24608)
-- Name: xe_may_dien; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.xe_may_dien (
    id_xe_may_dien bigint NOT NULL,
    gia double precision,
    hinh_anh text,
    mo_ta character varying(500),
    so_luong integer NOT NULL,
    ten_xemd character varying(100),
    id_nha_cung_cap bigint
);


ALTER TABLE public.xe_may_dien OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24607)
-- Name: xe_may_dien_id_xe_may_dien_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.xe_may_dien ALTER COLUMN id_xe_may_dien ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xe_may_dien_id_xe_may_dien_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4873 (class 0 OID 24578)
-- Dependencies: 216
-- Data for Name: don_hang; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.don_hang (id_don_hang, ngay_dat, id_khach_hang, id_tai_khoan, id_trang_thai) FROM stdin;
\.


--
-- TOC entry 4875 (class 0 OID 24584)
-- Dependencies: 218
-- Data for Name: khach_hang; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.khach_hang (id_khach_hang, dia_chi, email, so_dien_thoai, ten_khach_hang) FROM stdin;
1	Đồng Tháp	duy@gmail.com	0987654321	Võ Hoàng Duy
2	Tây Ninh	an@gmail.com	0901234567	Trần An Hạ
3	Đồng Tháp	duy@gmail.com	0987654321	Võ Hoàng Yến
4	Tây Ninh	duy@gmail.com	0987654321	Nguyễn Hoàng Nam
\.


--
-- TOC entry 4877 (class 0 OID 24590)
-- Dependencies: 220
-- Data for Name: nhacc; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.nhacc (id_nha_cung_cap, dia_chi, email, so_dien_thoai, ten_nha_cung_cap) FROM stdin;
43	TP.HCM	yadea@example.com	0901234567	Yadea Việt Nam
6	An Phú	vangcongtin@gmail.com	0334559101	An Giang
44	Hà Nội	jvc@gmail.com	0899764321	E-Scooter JVC
45	Hà Nội	nijia@gmail.com	0867664321	NIJIA
47	Đồng Tháp	hkbike@gmail.com	0901234567	HKBIKE
\.


--
-- TOC entry 4879 (class 0 OID 24596)
-- Dependencies: 222
-- Data for Name: tai_khoan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tai_khoan (id_tai_khoan, email, mat_khau, tentk, vai_tro) FROM stdin;
1	vangcongtin@gmail.com	123	tin	admin
3	vangcongtin@gmail.com	123	tinvang	admin
\.


--
-- TOC entry 4881 (class 0 OID 24602)
-- Dependencies: 224
-- Data for Name: trang_thaidh; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trang_thaidh (id_trang_thai, ten) FROM stdin;
2	Đã Hoàn Thành
3	Chờ Xác Nhận 
4	Đang Giao
\.


--
-- TOC entry 4883 (class 0 OID 24608)
-- Dependencies: 226
-- Data for Name: xe_may_dien; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.xe_may_dien (id_xe_may_dien, gia, hinh_anh, mo_ta, so_luong, ten_xemd, id_nha_cung_cap) FROM stdin;
10	17190000	https://xedien.vn/wp-content/uploads/2024/09/F1New_DenTemDoBong.jpg	 Xe đạp điện YADEA IGO sử dụng pin Lithium gọn nhẹ chỉ 6kg được lắp dưới yên, có thể tháo lắp pin dễ dàng để sạc tiện lợi và nhanh chóng. Pin Lithium có độ bền và tuổi thọ cao hơn ắc quy thông thường từ 1 đến 2 năm.	18	Xe Máy Điện E-Scooter JVC Xmen F1 New	44
11	14090000	https://xedien.vn/wp-content/uploads/2024/06/G9S_NFC_DoAnhDao.jpg		25	Xe Máy Điện E-Scooter JVC G9S NFC	\N
12	13690000	https://xedien.vn/wp-content/uploads/2023/10/I8_XanhDaTroi-1-600x600.jpg		50	Xe Máy Điện E-scooter YADEA I8 2024	43
6	16490000	https://xedien.vn/wp-content/uploads/2021/04/yadea-ulike-%C4%91en-v%C3%A0ng-850.jpg	Xe máy điện YADEA Ulike là một phiên bản xe máy điện có khả năng vận hành bức tốc cùng với những tính năng hiện đại và tiện ích được tích hợp trên xe. Những tính năng nổi bật cùng với ngoại hình đáng yêu, thu hút đã làm xe máy điện YADEA Ulike rạng ngời và di chuyển rất linh hoạt mỗi khi xuống phố.	13	Xe Máy Điện E-SCOOTER YADEA Ulike	43
7	18190000	https://xedien.vn/wp-content/uploads/2024/07/VespaPlatinumNFC_XamXiMang_2.jpg		6	Xe Máy Điện E-Scooter JVC Vespa Platinum NFC	44
8	13990000	https://xedien.vn/wp-content/uploads/2022/03/%C4%91o%CC%89-768x768.jpg	Với thiết kế cổ điển, sang trọng mang âm hưởng của dòng xe Vespa nổi tiếng từ nước Ý, Xe máy điện NIJIA Vespa Venus có khả năng vận hành ấn tượng cùng gu thời trang sang chảnh sẽ là sự lựa chọn hàng đầu cho sản phẩm “phương tiện xanh” dành cho các bạn trẻ hướng tới phong cách trẻ trung, hiện đạị.	9	Xe Máy Điện E-SCOOTER NIJIA Venus LX – 2022	45
5	12690000	https://xedien.vn/wp-content/uploads/2021/03/Yadea-igo-den-fix.jpg	Xe đạp điện YADEA IGO có tổng thể nhỏ gọn, thiết kế thời trang với bộ tem trẻ trung năng động. Mẫu xe đạp điện này được học sinh cấp 2, cấp 3 yêu thích với màu sắc bắt mắt và chiều cao lý tưởng và rất gọn nhẹ chỉ hơn 40kg.\n\nXe đạp điện YADEA IGO sử dụng pin Lithium gọn nhẹ chỉ 6kg được lắp dưới yên, có thể tháo lắp pin dễ dàng để sạc tiện lợi và nhanh chóng. Pin Lithium có độ bền và tuổi thọ cao hơn ắc quy thông thường từ 1 đến 2 năm.	190	Xe Máy Điện E-Bike YADEA IGO 2024 Vip Ver 2	43
9	10000000	https://xedien.vn/wp-content/uploads/2021/04/M6I_Pink.jpg	Xe máy điện YADEA M6i là dòng xe máy điện với thiết kế đậm chất nữ tính, mang phong cách hiện đại và thời trang. Những tính năng nổi bật cùng với ngoại hình bắt mắt đã làm xe máy điện YADEA M6i rạng ngời thu hút mọi ánh nhìn mỗi khi xuống phố. Đây là dòng xe máy điện được thương hiệu YADEA chăm chút trong từng chi tiết từ thiết kế đến các tính năng.	12	Xe Máy Điện E-SCOOTER YADEA M6I	43
\.


--
-- TOC entry 4889 (class 0 OID 0)
-- Dependencies: 215
-- Name: don_hang_id_don_hang_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.don_hang_id_don_hang_seq', 1, false);


--
-- TOC entry 4890 (class 0 OID 0)
-- Dependencies: 217
-- Name: khach_hang_id_khach_hang_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.khach_hang_id_khach_hang_seq', 4, true);


--
-- TOC entry 4891 (class 0 OID 0)
-- Dependencies: 219
-- Name: nhacc_id_nha_cung_cap_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.nhacc_id_nha_cung_cap_seq', 48, true);


--
-- TOC entry 4892 (class 0 OID 0)
-- Dependencies: 221
-- Name: tai_khoan_id_tai_khoan_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tai_khoan_id_tai_khoan_seq', 5, true);


--
-- TOC entry 4893 (class 0 OID 0)
-- Dependencies: 223
-- Name: trang_thaidh_id_trang_thai_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trang_thaidh_id_trang_thai_seq', 5, true);


--
-- TOC entry 4894 (class 0 OID 0)
-- Dependencies: 225
-- Name: xe_may_dien_id_xe_may_dien_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.xe_may_dien_id_xe_may_dien_seq', 14, true);


--
-- TOC entry 4714 (class 2606 OID 24582)
-- Name: don_hang don_hang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.don_hang
    ADD CONSTRAINT don_hang_pkey PRIMARY KEY (id_don_hang);


--
-- TOC entry 4716 (class 2606 OID 24588)
-- Name: khach_hang khach_hang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.khach_hang
    ADD CONSTRAINT khach_hang_pkey PRIMARY KEY (id_khach_hang);


--
-- TOC entry 4718 (class 2606 OID 24594)
-- Name: nhacc nhacc_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nhacc
    ADD CONSTRAINT nhacc_pkey PRIMARY KEY (id_nha_cung_cap);


--
-- TOC entry 4720 (class 2606 OID 24600)
-- Name: tai_khoan tai_khoan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tai_khoan
    ADD CONSTRAINT tai_khoan_pkey PRIMARY KEY (id_tai_khoan);


--
-- TOC entry 4722 (class 2606 OID 24606)
-- Name: trang_thaidh trang_thaidh_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trang_thaidh
    ADD CONSTRAINT trang_thaidh_pkey PRIMARY KEY (id_trang_thai);


--
-- TOC entry 4724 (class 2606 OID 24614)
-- Name: xe_may_dien xe_may_dien_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.xe_may_dien
    ADD CONSTRAINT xe_may_dien_pkey PRIMARY KEY (id_xe_may_dien);


--
-- TOC entry 4725 (class 2606 OID 24625)
-- Name: don_hang fk91sww1575i2ytyg0c8s64uou2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.don_hang
    ADD CONSTRAINT fk91sww1575i2ytyg0c8s64uou2 FOREIGN KEY (id_trang_thai) REFERENCES public.trang_thaidh(id_trang_thai);


--
-- TOC entry 4726 (class 2606 OID 24620)
-- Name: don_hang fka45yjwnhbg7rxl0am9x1m36k3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.don_hang
    ADD CONSTRAINT fka45yjwnhbg7rxl0am9x1m36k3 FOREIGN KEY (id_tai_khoan) REFERENCES public.tai_khoan(id_tai_khoan);


--
-- TOC entry 4728 (class 2606 OID 24630)
-- Name: xe_may_dien fkgqkmxwefx62gpbpoxdjw5986p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.xe_may_dien
    ADD CONSTRAINT fkgqkmxwefx62gpbpoxdjw5986p FOREIGN KEY (id_nha_cung_cap) REFERENCES public.nhacc(id_nha_cung_cap);


--
-- TOC entry 4727 (class 2606 OID 24615)
-- Name: don_hang fkmivw7ljk89ubdoaox17upk6c1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.don_hang
    ADD CONSTRAINT fkmivw7ljk89ubdoaox17upk6c1 FOREIGN KEY (id_khach_hang) REFERENCES public.khach_hang(id_khach_hang);


-- Completed on 2024-10-13 17:18:55

--
-- PostgreSQL database dump complete
--

